/* Unique id generation */
import uuid from "utils/uuid";

/* Pull in all your components for both main and sets here */
import NewGame from "games/NewGame"
import Waiting from "games/NewGame/Phases/Waiting"

/* You can add custom functions here */
const getAvatar = () => {
  return "🐲"
}

export const game = {
  title: 'NewGame', //Title is used in HTML heading
  route: 'newgame', //Route to get to this game
  description: 'The game where knowing the right answer, is only half the challenge.',
  main: <NewGame /> //Main entry point component
}

export const playerStructure = {
  id: uuid(), //Generate uuuid
  name: { input: true }, //Means you are expecting user input
  leader: { initial: true, default: false }, //Initial will be the default for new portals, default will be the default for players joining already made portals
  avatar: getAvatar(), //You can add your own custom functions inside game.config.js
}

export const portalStructure = {
  phase: 'waiting', //Code will break if you do not include phases, but you could have just one phase
  players: [], //You need to have an array of players
}
//The "set" that is displayed is determined by "phase" of the current portal, make sure to import these components
//Examples of sets shown below
export const sets = {
  waiting: <Waiting key="Waiting"/>,
  // question: <Questions key="Questions"/>,
  // answer: <Answer key="Answer"/>
};

export const state = {
  _id: null, //ID is autogenerated and must be included here
  code: null, //Code is autogenerated and must be included here
  game: null, //Game is autogenerated and must be included here
  phase: null, //Phase is require for the Game Stage to work
  players: null, //Players are required
}
